update README, update flake, fix 'since's
Liqwid-Labs/plutarch-benchmark pull request #4
Opened 2022-08-19 21:17 UTC by peter-mlabs

Can you give this a quick look and make sure I'm not misunderstanding anything? Thanks!

2022-08-19 21:18 UTC, peter-mlabs commented
Closes #3

2022-08-21 20:48 UTC, cjay requested changes
The rest looks good.

2022-08-21 20:48 UTC, cjay commented on README.md
> +and script size, and ranks those implementations in terms of best, worst,
The script size is only in the metadata currently, it doesn't get ranked.

2022-08-21 20:48 UTC, cjay commented on README.md
> +  metadata about the size of the input it was generated from,
inputs

2022-08-21 20:48 UTC, cjay commented on README.md
> +  a pair of generators: exhaustive generators for small samples sizes,
small input sizes (also next line)

2022-08-23 00:32 UTC, peter-mlabs commented
Thanks @cjay! I'm going to open an issue to add script size to the benchmarking, but its not a high priority right now.

2022-08-23 02:52 UTC, cjay approved these changes

2022-08-23 14:47 UTC, merged